import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { FormEvent } from "react";
import styles from "../styles/Home.module.css";
import { Octokit } from "@octokit/core";

const onSend = async (evt: FormEvent<HTMLFormElement>) => {
  evt.preventDefault();

  let formData = Object.fromEntries(
    new FormData(evt.target as HTMLFormElement).entries()
  );

  console.log("on send", formData);

  const octokit = new Octokit({
    auth: process.env.NEXT_PUBLIC_AUTH_TOKEN,
  });
  let data = await octokit.request("POST /repos/{owner}/{repo}/issues", {
    owner: "zlypher",
    repo: "gh-issue-ui",
    title: "Test Title",
    body: "Test Body",
  });
  console.log(data);
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={onSend}>
          <div>
            <label htmlFor="title"></label>
            <input id="title" name="title" type="text" />
          </div>
          <div>
            <label htmlFor="description"></label>
            <textarea id="description" name="description" />
          </div>
          <input type="submit" value="Send" />
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
